# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='passwords',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='hh', max_length=20),
        ),
    ]
