# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170411_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='passwords',
            new_name='password',
        ),
    ]
